// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZ9BGwmax_CDX1fOvWdYBvf4IGhiyTac',
    appId: '1:691658847178:web:34a50752cc36e5dfec5533',
    messagingSenderId: '691658847178',
    projectId: 'benefit-on',
    authDomain: 'benefit-on.firebaseapp.com',
    storageBucket: 'benefit-on.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbLgl139IUPDEXbdxySL29zR8wr1IFIcg',
    appId: '1:691658847178:android:dbd4ce175ad4d49cec5533',
    messagingSenderId: '691658847178',
    projectId: 'benefit-on',
    storageBucket: 'benefit-on.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJto5Bd6ul8BaIWHd4xoCuNpjhitxP0BY',
    appId: '1:691658847178:ios:260b28707a6d809cec5533',
    messagingSenderId: '691658847178',
    projectId: 'benefit-on',
    storageBucket: 'benefit-on.firebasestorage.app',
    iosBundleId: 'com.benefit.app',
  );
}
